export const jwtConstants = {
  secret:
    'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};

export enum ErrorTypes {
  INVALID_MONGO_ID_FORMAT = '400001',
  INVALID_DTO_FORMAT = '400002',
  SCHEMA_VALIDATION_ERROR = '400003',
  DEPENDEND_DOCUMENT_NOT_FOUND = '400004',
  INVALID_CREDENTIALS = '401001',
  NO_ACCESS_RIGHTS_TO_RESOURCE = '403001',
  NO_ACCESS_RIGHTS_TO_DEPENDENT_RESOURCE = '403002',
  DOCUMENT_NOT_FOUND = '404001',
  DUPLICATED_KEY_INDEX_ERROR = '409001',
  DELETE_BLOCKED_BY_DEPENDENT_RESOURCE = '409002',
}

export enum StatusMessages {
  OK = 'ok',
}
