# ci-pipeline for services
name: SERVICES-CI
on: 
  push:
    paths:
      - backend/campaign-service/**
      - .github/workflows/campaign-service-actions.yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
    
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
    
      - name: Install dependencies
        run: yarn
        working-directory: ./backend/campaign-service
    
      - name: Run tests
        run: yarn test
        working-directory: ./backend/campaign-service
  sast:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'